id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_0,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_0,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,passed,,0.0001152500044554472
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_1,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_1,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,passed,,8.729100227355957e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_2,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_2,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,8.720901678316295e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_3,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_3,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,9.399998816661537e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_4,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_4,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,8.008300210349262e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_5,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_5,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,"assert {} == -3327.6 ± 33.276
  
  comparison failed
  Obtained: {}
  Expected: -3327.6 ± 33.276",0.00024379100068472326
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_6,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_6,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,passed,,6.583301001228392e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_7,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_7,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,passed,,6.0040998505428433e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_8,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_8,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,7.837501470930874e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_9,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_9,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,7.837501470930874e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_10,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_10,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'TypeError'>,7.558299694210291e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_11,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_11,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,7.562499376945198e-05
functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py::test_case_12,functional_correctness_test_folder.csn.openai.no_docstr.test_snippet_247,test_case_12,functional_correctness_test_folder/csn/openai/no_docstr/test_snippet_247.py,,,failed,Failed: DID NOT RAISE <class 'ValueError'>,7.379200542345643e-05
