id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/post_cut-off/rag/meta-llama/full_docstr/test_snippet_183.py::test_case_0,functional_correctness_test_folder.post_cut-off.rag.meta-llama.full_docstr.test_snippet_183,test_case_0,functional_correctness_test_folder/post_cut-off/rag/meta-llama/full_docstr/test_snippet_183.py,,,failed,TypeError: InferenceConfig.__init__() got an unexpected keyword argument 'max_steps',8.458294905722141e-05
functional_correctness_test_folder/post_cut-off/rag/meta-llama/full_docstr/test_snippet_183.py::test_case_1,functional_correctness_test_folder.post_cut-off.rag.meta-llama.full_docstr.test_snippet_183,test_case_1,functional_correctness_test_folder/post_cut-off/rag/meta-llama/full_docstr/test_snippet_183.py,,,failed,TypeError: InferenceConfig.__init__() got an unexpected keyword argument 'server_max_workers',8.945795707404613e-05
functional_correctness_test_folder/post_cut-off/rag/meta-llama/full_docstr/test_snippet_183.py::test_case_2,functional_correctness_test_folder.post_cut-off.rag.meta-llama.full_docstr.test_snippet_183,test_case_2,functional_correctness_test_folder/post_cut-off/rag/meta-llama/full_docstr/test_snippet_183.py,,,failed,TypeError: InferenceConfig.__init__() got an unexpected keyword argument 'split',0.0010199170792475343
