id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py::test_case_0,functional_correctness_test_folder.csn.gpt-4.1.no_docstr.test_snippet_157,test_case_0,functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py,,xfail,xfailed,,9.47499938774854e-05
functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py::test_case_1,functional_correctness_test_folder.csn.gpt-4.1.no_docstr.test_snippet_157,test_case_1,functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py,,xfail,xfailed,,0.00019550000433810055
functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py::test_case_2,functional_correctness_test_folder.csn.gpt-4.1.no_docstr.test_snippet_157,test_case_2,functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py,,,failed,AttributeError: type object 'HashMixin' has no attribute 'encrypt_sql'. Did you mean: 'get_encrypt_sql'?,0.0001423330104444176
functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py::test_case_3,functional_correctness_test_folder.csn.gpt-4.1.no_docstr.test_snippet_157,test_case_3,functional_correctness_test_folder/csn/gpt-4.1/no_docstr/test_snippet_157.py,,,failed,AttributeError: type object 'HashMixin' has no attribute 'encrypt_sql'. Did you mean: 'get_encrypt_sql'?,9.345798753201962e-05
