id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/post_cut-off/gpt-4.1/no_docstr/test_snippet_369.py::test_case_0,functional_correctness_test_folder.post_cut-off.gpt-4.1.no_docstr.test_snippet_369,test_case_0,functional_correctness_test_folder/post_cut-off/gpt-4.1/no_docstr/test_snippet_369.py,,xfail,failed,[XPASS(strict)] ,0.00025679299142211676
functional_correctness_test_folder/post_cut-off/gpt-4.1/no_docstr/test_snippet_369.py::test_case_1,functional_correctness_test_folder.post_cut-off.gpt-4.1.no_docstr.test_snippet_369,test_case_1,functional_correctness_test_folder/post_cut-off/gpt-4.1/no_docstr/test_snippet_369.py,,,passed,,0.0002752639993559569
functional_correctness_test_folder/post_cut-off/gpt-4.1/no_docstr/test_snippet_369.py::test_case_2,functional_correctness_test_folder.post_cut-off.gpt-4.1.no_docstr.test_snippet_369,test_case_2,functional_correctness_test_folder/post_cut-off/gpt-4.1/no_docstr/test_snippet_369.py,,,failed,Failed: DID NOT RAISE <class 'RuntimeError'>,0.0003056789864785969
