id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/csn/gpt-4.1/full_docstr/test_snippet_158.py::test_case_0,functional_correctness_test_folder.csn.gpt-4.1.full_docstr.test_snippet_158,test_case_0,functional_correctness_test_folder/csn/gpt-4.1/full_docstr/test_snippet_158.py,,,failed,Failed: DID NOT RAISE <class 'NotImplementedError'>,9.850000060396269e-05
functional_correctness_test_folder/csn/gpt-4.1/full_docstr/test_snippet_158.py::test_case_1,functional_correctness_test_folder.csn.gpt-4.1.full_docstr.test_snippet_158,test_case_1,functional_correctness_test_folder/csn/gpt-4.1/full_docstr/test_snippet_158.py,,,failed,AttributeError: 'bytes' object has no attribute 'data',9.291600144933909e-05
functional_correctness_test_folder/csn/gpt-4.1/full_docstr/test_snippet_158.py::test_case_2,functional_correctness_test_folder.csn.gpt-4.1.full_docstr.test_snippet_158,test_case_2,functional_correctness_test_folder/csn/gpt-4.1/full_docstr/test_snippet_158.py,,,failed,UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 0: invalid continuation byte,9.116699948208407e-05
