id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/csn/openai/partial_docstr/test_snippet_178.py::test_case_0,functional_correctness_test_folder.csn.openai.partial_docstr.test_snippet_178,test_case_0,functional_correctness_test_folder/csn/openai/partial_docstr/test_snippet_178.py,,,failed,AttributeError: type object 'TableCell' has no attribute 'alignment',8.808300481177866e-05
functional_correctness_test_folder/csn/openai/partial_docstr/test_snippet_178.py::test_case_1,functional_correctness_test_folder.csn.openai.partial_docstr.test_snippet_178,test_case_1,functional_correctness_test_folder/csn/openai/partial_docstr/test_snippet_178.py,,,failed,AttributeError: type object 'TableCell' has no attribute 'alignment',7.958299829624593e-05
functional_correctness_test_folder/csn/openai/partial_docstr/test_snippet_178.py::test_case_2,functional_correctness_test_folder.csn.openai.partial_docstr.test_snippet_178,test_case_2,functional_correctness_test_folder/csn/openai/partial_docstr/test_snippet_178.py,,,failed,AttributeError: type object 'TableCell' has no attribute 'alignment',0.00010562498937360942
