id,module,name,file,doc,markers,status,message,duration
functional_correctness_test_folder/post_cut-off/rag/openai/partial_docstr/test_snippet_61.py::test_case_0,functional_correctness_test_folder.post_cut-off.rag.openai.partial_docstr.test_snippet_61,test_case_0,functional_correctness_test_folder/post_cut-off/rag/openai/partial_docstr/test_snippet_61.py,,,failed,TypeError: Program.__init__() got an unexpected keyword argument 'generation',8.633302059024572e-05
